'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Bookmark, ChevronRight, Clock3, Globe2, Menu, Search, Send, Share2, Star, MessageCircle, X, PlayCircle, Headphones, MapPin } from 'lucide-react'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/burkina_news_horizontal-3B7hzN9uWlJzKrHlzpgvxJaQ0ISw3N.png'
const images = { lead: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=85', people: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=85', work: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85', city: 'https://images.unsplash.com/photo-1494522358652-f30e61a60313?auto=format&fit=crop&w=900&q=85' }
const stories = [
  { category: 'Politique', title: 'Le Burkina Faso accélère sa marche vers une souveraineté assumée', excerpt: 'Les grandes décisions de la semaine et les nouvelles orientations pour le pays.', time: 'Il y a 18 min', image: images.lead, lead: true },
  { category: 'Économie', title: 'Ces jeunes qui transforment les défis en opportunités', excerpt: 'Portraits et initiatives qui font bouger les lignes.', time: 'Il y a 42 min', image: images.work },
  { category: 'Société', title: 'Ouagadougou, une ville en mouvement racontée par ses habitants', excerpt: 'Regards croisés sur les mutations de la capitale.', time: 'Il y a 1 h', image: images.city },
  { category: 'Culture', title: 'La création burkinabè s’exporte et inspire le continent', excerpt: 'Artistes, créateurs et nouvelles scènes à découvrir.', time: 'Il y a 2 h', image: images.people },
  { category: 'Sport', title: 'Les Étalons préparent leur prochain grand rendez-vous', excerpt: 'Dans les coulisses de la sélection nationale.', time: 'Il y a 3 h', image: images.work },
]
const briefs = [['08:45', 'La météo du jour : ciel clair sur les principales villes du pays'], ['08:12', 'Éducation : ouverture des inscriptions pour la prochaine rentrée'], ['07:50', 'Sport : les Étalons préparent leur prochain grand rendez-vous'], ['07:28', 'Culture : le rendez-vous des créateurs revient à Ouaga']]
const categories = ['À la une', 'Politique', 'Économie', 'Société', 'Culture', 'Sport', 'Sahel']

function SectionHeading({ children, action = 'Voir tout', onClick }: { children: React.ReactNode; action?: string; onClick?: () => void }) { return <div className="section-heading"><h2>{children}</h2><button onClick={onClick}>{action}<ChevronRight size={16} /></button></div> }
function StoryCard({ story, compact = false, onOpen }: { story: typeof stories[number]; compact?: boolean; onOpen?: () => void }) { const [saved, setSaved] = useState(false); return <article className={`story-card ${compact ? 'compact' : ''}`}><button className="story-open" onClick={onOpen} aria-label={`Lire : ${story.title}`}><div className="story-image"><img src={story.image} alt="" /><span>{story.category}</span></div><div className="story-copy"><div className="story-meta"><Clock3 size={13} /> {story.time}</div><h3>{story.title}</h3>{!compact && <p>{story.excerpt}</p>}</div></button><div className="story-actions"><button aria-label="Partager" onClick={() => navigator.clipboard?.writeText(story.title)}><Share2 size={15} /></button><button aria-label={saved ? 'Retirer des favoris' : 'Sauvegarder'} onClick={() => setSaved(!saved)} className={saved ? 'active' : ''}><Bookmark size={15} fill={saved ? 'currentColor' : 'none'} /></button></div></article> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false), [activeCategory, setActiveCategory] = useState('À la une'), [query, setQuery] = useState(''), [subscribed, setSubscribed] = useState(false), [view, setView] = useState('home')
  const filtered = useMemo(() => stories.filter(s => (!query || `${s.title} ${s.category}`.toLowerCase().includes(query.toLowerCase())) && (activeCategory === 'À la une' || s.category === activeCategory)), [query, activeCategory])
  const go = (next: string) => { setView(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <main>
    <div className="topline"><div className="container top-inner"><span>Jeudi 28 août 2026 · Ouagadougou</span><span className="top-note">L&apos;information juste, l&apos;info vraie</span><div className="top-social"><Globe2 size={14} /><MessageCircle size={14} /><PlayCircle size={14} /></div></div></div>
    <header className="site-header"><div className="container header-inner"><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Ouvrir le menu">{menuOpen ? <X /> : <Menu />}</button><button className="brand" onClick={() => go('home')}><img src={logoUrl} alt="Burkina News" /></button><div className="header-tools"><label className="search"><Search size={18} /><input value={query} onChange={e => { setQuery(e.target.value); setView('search') }} placeholder="Rechercher" aria-label="Rechercher une actualité" /></label><button className="newsletter-button" onClick={() => document.getElementById('newsletter')?.scrollIntoView({ behavior: 'smooth' })}>S&apos;abonner</button></div></div></header>
    <nav className={`category-nav ${menuOpen ? 'open' : ''}`} aria-label="Navigation principale"><div className="container category-inner">{categories.map(category => <button key={category} className={activeCategory === category && view === 'home' ? 'selected' : ''} onClick={() => { setActiveCategory(category); go(category === 'À la une' ? 'home' : 'category') }}>{category}</button>)}<span className="nav-rule" /><button onClick={() => go('video')} className="live"><span /> En direct</button></div></nav>
    {view === 'home' && <><div className="container breaking"><span className="breaking-label">Fil info</span><p>La nation debout : suivez toute l&apos;actualité du Burkina Faso en continu</p><ArrowRight size={17} /></div><section className="container hero-grid"><div className="hero-lead"><img src={images.lead} alt="Actualité politique au Burkina Faso" /><div className="hero-overlay"><span>À la une · Politique</span><h1>{stories[0].title}</h1><p>{stories[0].excerpt}</p><div className="byline">Burkina News <span>•</span> Il y a 18 min</div></div></div><aside className="brief-panel"><div className="brief-title"><span>Le fil du jour</span><span className="live-dot" /></div>{briefs.map(([time, text]) => <div className="brief" key={time}><time>{time}</time><p>{text}</p></div>)}<button className="all-briefs">Tout le fil <ArrowRight size={15} /></button></aside></section><section className="container content-section"><SectionHeading onClick={() => setActiveCategory('À la une')}>Les dernières actualités</SectionHeading><div className="news-grid">{filtered.slice(1, 3).map(story => <StoryCard key={story.title} story={story} />)}<div className="most-read"><div className="most-read-heading"><Star size={17} fill="currentColor" /> <span>Les plus lus</span></div>{['Ce qu’il faut retenir cette semaine', 'Les nouveaux visages de l’entrepreneuriat', 'Les rendez-vous culturels à ne pas manquer'].map((item, index) => <div className="ranking" key={item}><strong>0{index + 1}</strong><p>{item}</p></div>)}</div></div></section><section className="container content-section"><SectionHeading action="Explorer la rubrique" onClick={() => setActiveCategory('Société')}>Regards & société</SectionHeading><div className="society-grid"><StoryCard story={stories[2]} compact /><StoryCard story={stories[3]} compact /><div className="quote-card"><div className="quote-mark">“</div><p>Informer, c&apos;est donner à chacun les moyens de comprendre et d&apos;agir.</p><span>— La rédaction</span></div></div></section><section className="container format-strip"><div><span className="eyebrow">Nouveau format</span><h2>Les voix du pays</h2><p>Un podcast pour entendre celles et ceux qui font le Burkina d&apos;aujourd&apos;hui.</p></div><button onClick={() => go('podcast')}><Headphones size={18} /> Écouter l&apos;épisode</button></section></>}
    {view === 'category' && <section className="container page-view category-view"><span className="eyebrow">Rubrique · Édition Burkina News</span><h1>{activeCategory}</h1><p className="page-intro">Toute l’actualité de la rubrique {activeCategory.toLowerCase()}, sélectionnée et expliquée par notre rédaction.</p><div className="category-layout"><div className="archive-grid">{filtered.length ? filtered.map(s => <StoryCard key={s.title} story={s} onOpen={() => go('article')} />) : stories.map(s => <StoryCard key={s.title} story={{...s, category: activeCategory}} onOpen={() => go('article')} />)}</div><aside className="category-aside"><span className="eyebrow">À retenir</span><h2>Le regard de la rédaction</h2><p>Des faits, du contexte et des voix locales pour mieux comprendre ce qui se joue au Burkina Faso.</p><button className="all-briefs" onClick={() => go('about')}>Notre méthode <ArrowRight size={15} /></button></aside></div></section>}
    {view === 'article' && <section className="container article-view page-view"><span className="eyebrow">{stories[0].category} · Analyse</span><h1>{stories[0].title}</h1><div className="article-meta"><Clock3 size={14} /> Publié il y a 18 min · Par la rédaction Burkina News</div><img className="article-image" src={stories[0].image} alt="Illustration de l’actualité au Burkina Faso" /><div className="article-body"><p className="article-lead">{stories[0].excerpt} Une lecture approfondie pour suivre les transformations qui façonnent le pays.</p><p>Au fil des décisions et des initiatives, une nouvelle dynamique se dessine. Dans les quartiers, les institutions et les territoires, les Burkinabè inventent des réponses concrètes aux enjeux du quotidien.</p><blockquote>« Informer avec justesse, c’est rendre le réel plus lisible. »</blockquote><p>Burkina News donne la parole aux acteurs concernés et met les faits en perspective. Cet article est une démonstration éditoriale basée sur des données mockées.</p><div className="article-actions"><button className="newsletter-button" onClick={() => navigator.clipboard?.writeText(stories[0].title)}><Share2 size={16} /> Partager</button><button className="outline-button" onClick={() => go('home')}>Retour aux actualités</button></div></div></section>}
    {view === 'search' && <section className="container page-view"><span className="eyebrow">Recherche</span><h1>Résultats pour « {query || 'toute l’actualité'} »</h1><div className="archive-grid">{filtered.map(s => <StoryCard key={s.title} story={s} />)}</div>{!filtered.length && <div className="empty"><Search size={32} /><h2>Aucun résultat</h2><p>Essayez un autre mot-clé ou explorez nos rubriques.</p></div>}</section>}
    {(view === 'video' || view === 'podcast') && <section className="container page-view"><span className="eyebrow">{view === 'video' ? 'Vidéo · En direct' : 'Podcast · Les voix du pays'}</span><h1>{view === 'video' ? 'L’actualité en images' : 'Écouter le Burkina'}</h1><div className="media-feature"><img src={images.people} alt="Production éditoriale Burkina News" /><div><span className="play-badge">{view === 'video' ? <PlayCircle /> : <Headphones />}</span><h2>{view === 'video' ? 'Les images qui racontent l’actualité nationale' : 'Épisode 01 · Nos villes, nos histoires'}</h2><p>Un format original Burkina News, produit par notre rédaction. Contenu de démonstration.</p><button className="newsletter-button">Lancer le format <ArrowRight size={16} /></button></div></div><SectionHeading>À découvrir ensuite</SectionHeading><div className="archive-grid">{stories.slice(1).map(s => <StoryCard key={s.title} story={s} />)}</div></section>}
    {view === 'about' && <section className="container page-view about-view"><span className="eyebrow">Notre rédaction</span><h1>Comprendre le Burkina, raconter le réel.</h1><p className="intro">Burkina News est un média indépendant qui place la rigueur, la proximité et la dignité des personnes au cœur de son travail.</p><div className="about-columns"><div><MapPin size={22} /><h2>Depuis Ouagadougou</h2><p>Une rédaction ancrée dans les territoires, attentive aux voix qui construisent le pays.</p></div><div><Star size={22} /><h2>Notre promesse</h2><p>Des informations vérifiées, expliquées et accessibles à toutes et tous.</p></div></div></section>}
    <section id="newsletter" className="newsletter container"><div><span className="eyebrow">La lettre Burkina News</span><h2>L&apos;essentiel de l&apos;actualité, dans votre boîte.</h2><p>Une sélection claire et indépendante, chaque semaine.</p></div>{subscribed ? <div className="subscribed"><Star size={18} /> Merci, vous êtes inscrit.</div> : <form onSubmit={e => { e.preventDefault(); setSubscribed(true) }}><input type="email" required placeholder="Votre adresse email" aria-label="Votre adresse email" /><button type="submit">Je m&apos;inscris <Send size={16} /></button></form>}</section>
    <footer><div className="container footer-inner"><div className="footer-brand"><img src={logoUrl} alt="Burkina News" /><p>Le média qui donne du sens à l&apos;actualité burkinabè.</p></div><div><span className="footer-label">Explorer</span><button onClick={() => go('home')}>À la une</button><button onClick={() => go('video')}>Vidéos</button><button onClick={() => go('podcast')}>Podcasts</button></div><div><span className="footer-label">La rédaction</span><button onClick={() => go('about')}>À propos</button><p>Ouagadougou, Burkina Faso</p></div></div><div className="container copyright">© 2026 Burkina News · Tous droits réservés <span>Mentions légales</span><span>Contact</span></div></footer>
  </main>
}
